services:
#  demo:
#    build:
#      context: ./demo
#      dockerfile: Dockerfile
#
#    container_name: demo
#
#    ports:
#      - "8080:8080"
#  ========================
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile

    container_name: user-service

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8081:8080"
# =========================
  hotel-service:
    build:
      context: ./hotel-service
      dockerfile: Dockerfile

    container_name: hotel-service

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8082:8080"
#  ========================
  user-db:
    image: postgres:17
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

    ports:
      - "5433:5432"

    volumes:
      - user-db-data:/var/lib/postgresql/data
#  ========================
  hotel-db:
    image: postgres:17
    container_name: hotel-db
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

    ports:
      - "5434:5432"

    volumes:
      - hotel-db-data:/var/lib/postgresql/data
#  ========================
volumes:
  user-db-data:
  hotel-db-data: