services:
#  demo:
#    build:
#      context: ./demo
#      dockerfile: Dockerfile
#
#    container_name: demo
#
#    ports:
#      - "8080:8080"
#  ========================
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile

    container_name: user-service

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8081:8081"
#  ========================
  user-db:
    image: postgres:17
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

    ports:
      - "5433:5432"

    volumes:
      - user-db-data:/var/lib/postgresql/data

volumes:
  user-db-data: